[window_mode]
width = 1200.0
height = 1200.0
maximized = false
fullscreen_type = "Windowed"
borderless = false
min_width = 0.0
min_height = 0.0
max_width = 0.0
max_height = 0.0
resizable = false
visible = true
resize_on_scale_factor_change = false

[window_setup]
title = "AoC 2021 day 13"
samples = "One"
vsync = true
icon = ""
srgb = true

[backend]
type = "OpenGL"
major = 3
minor = 2

[modules]
gamepad = true
audio = true
