[package]
name = "day-11-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-util = { path = "../../aoc-util" }
ggez = "0.9.3"
glam = "0.20.1"

[profile.dev]
opt-level = 1