[package]
name = "day-12-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-util = { path = "../../aoc-util" }
regex = '1.5.4'
lazy_static = '1.4.0'
